---
title: "Fever_Analysis"
author: "Jesse Garrett-Larsen"
date: "2024-01-29"
output: html_document
---
Read in + format data
```{r}
rm(list=ls())

library(ggplot2)
library(tidyverse)
library(lme4)
library(glmmTMB)
library(effects)

ti <- read.csv("ti_merged_data.csv")

#Add column for total eye score by adding l and r eye score
ti <- ti %>%
  group_by(bird_ID) %>%
  mutate(total_eye_score=(l_eye_score+r_eye_score))

#make total eye score an integer by multiplying by two for models
ti$tes <- ti$total_eye_score*2

ti$threshold_cutoff = 100
ti$sympt_cutoff = 0.1


ti <- ti %>%
  mutate(infected = ifelse(quantity>threshold_cutoff, 1, 0))  #generate infection data; if path load > 50 copies = infected

#new column with whether the bird is ever infected
ti <- ti %>%
  group_by(band_number) %>%
  mutate(ever_infected = ifelse(any(coalesce(infected, 0) == 1), 1, 0)) %>%
  ungroup()

#new column with whether the bird is diseased on a particular day
ti <- ti %>%
  mutate(diseased= ifelse(total_eye_score>sympt_cutoff, 1, 0), na.rm=T)


#new column with whether the bird is ever diseased
ti <- ti %>%
  group_by(band_number) %>%
  mutate(ever_diseased = ifelse(any(coalesce(diseased, 0) == 1), 1, 0), na.rm=T) %>%
  ungroup()

#Add column for fever score by finding average score
ti <- ti %>%
  group_by(bird_ID) %>%
  mutate(fever_score=((((l_min + l_max)/2) + (r_min + r_max)/2)/2))

ti.tr <- ti %>%
  drop_na (band_number, fever_score, dpi, treatment, temp, groups, sex)

#fever change from baseline
ti.f <- ti.tr %>%
  group_by(band_number) %>%
  mutate(fever_change = fever_score - first(fever_score))

#fever change from previous score
ti.f <- ti.f %>%
  group_by(band_number) %>%
  mutate(fever_diff = fever_score - lag(fever_score))

#missing 2684 after it died on dpi 28
#2648 dpi 35 - pictures not taken
#2632 dpi 28 - pictures not taken
```

I used generalized linear mixed models with a gaussian distribution to test whether temperature or treatment with MG affected change in fever scores from pre-infection baseline fever scores.
```{r}
# AGA - add dpi as a fixed effect

ti.f$dpi <- as.factor(ti.f$dpi)

lm1 <- lmer(fever_score ~ temp*treatment*dpi + (1|band_number),data=ti.f)

car::Anova(lm1, type = "III")
hist(residuals(lm1))
plot(residuals(lm1), predict(lm1))


#AGA - stepwise selection:
car::Anova(lm1, type = "III")

lm2 <- lmer(fever_change ~ temp + treatment + dpi + 
                            treatment:dpi + temp:dpi + 
                              temp:treatment + (1|band_number),data=ti.f)

car::Anova(lm2, type = "III")

# Keep two-way interactions

plot(allEffects(lm2))

library(emmeans)
library(multcomp)
cld(emmeans(lm2, pairwise ~ dpi:treatment, adjust = "tukey"))

means <- as.data.frame(cld(emmeans(lm2, pairwise ~ dpi:treatment, adjust = "tukey")))

ggplot(means, aes(x = dpi, y = emmean, color = treatment))+
  geom_line(aes(group = treatment))+
  geom_point()


cld(emmeans(lm2, pairwise ~ dpi:temp, adjust = "tukey"))

means2 <- as.data.frame(cld(emmeans(lm2, pairwise ~ dpi:temp, adjust = "tukey")))

ggplot(means2, aes(x = dpi, y = emmean, color = temp))+
  geom_line(aes(group = temp))+
  geom_point()

ti.f$pred <- predict(lm2)

ti.fMeans <- ti.f %>% group_by(dpi, treatment, temp) %>%
  summarize(meanFevCh = mean(pred))

ggplot(ti.fMeans, aes(x = dpi, y = meanFevCh))+
geom_line(aes(group = treatment, color = treatment),
          linewidth = 1.2)+
geom_point(aes(color = treatment), size = 3)+
geom_jitter(data = ti.f, aes(x = dpi, y = fever_change, color = treatment), 
            alpha = 0.2,
            width = 0.1)+
theme_bw()+
facet_wrap(~temp)

####
summary(lm1)
plot(allEffects(lm1))

resid<-simulateResiduals(lm1)
plot(resid)

emm_results <- emmeans(lm1, ~ temp * treatment, scale="response", data=ti.f)
pairs(emm_results)

#model selection
e1 <- glm(fever_change ~temp+treatment + (1|band_number),data=ti.f)
e2 <- glm(fever_change ~temp+treatment + sex + (1|band_number),data=ti.f)
e3 <- glm(fever_change ~temp*treatment + (1|band_number),data=ti.f) 
e4 <- glm(fever_change ~temp*treatment + sex + (1|band_number),data=ti.f) 
e5 <- glm(fever_change ~temp + (1|band_number),data=ti.f)
e6 <- glm(fever_change ~treatment + (1|band_number),data=ti.f) 
e7 <- glm(fever_change ~1 + (1|band_number),data=ti.f)

aictab(cand.set=list(e1, e2,e3,e4,e6,e7),
       modnames=c("e1", "e2","e3","e4", "e6","e7"))

temp_names <- c(
  'Cold' = "Cold",
  'Warm' = "Warm"
)

ever_inf_names <- c(
  '0' = "Never Infected",
  '1' = "Infected"
)
table(ti.f$groups)
group_names <- c(
  'Cold Control' = "Cold Control",
  'Cold Infected' = "Cold Infected",
  'Warm Control' = "Warm Control",
  'Warm Infected' = "Warm Infected"
)

ggplot(data=ti.f, aes(x=dpi, y=fever_change, color = groups))+
  geom_jitter(aes(shape=treatment), size=1, width = 0.15)+
  geom_line(aes(x=dpi, y=fever_change, linetype=treatment, group=(band_number)), alpha=0.5, size=0.5)+
  stat_summary(aes(group=groups, linetype=treatment), fun=mean, geom="line", alpha=1, size=1)+
  stat_summary(aes(group=groups, linetype=treatment), fun=mean, geom="line", color="black", alpha=1, size=.5)+
  stat_summary(aes(group=groups), fun=mean,
               fun.min = function(x) mean(x)-sd(x),
               fun.max = function(x) mean(x)+sd(x),
               geom= "errorbar", size=0.5, width=0.25)+
  scale_color_manual(values=c("cyan3", "blue", "violet", "red"))+
  scale_x_continuous(breaks=unique(ti$dpi), labels=paste0(unique(ti$dpi)), limits = c(0,37))+
  scale_shape_manual(values=c(16, 1))+
  scale_linetype_manual(values=c("dashed", "solid"))+
  labs(x="Days Post Infection", y="Fever Score", 
       linetype= "Treatment", shape= "Treatment", color="Temperature")+
  facet_wrap(~groups, labeller = as_labeller(c(group_names)), scales="fixed")
```

```{r Variance}
glm.all <- glm(fever_change~1 +(1|band_number), data=ti.f)
glm.tnmg <- glm(fever_change~1 +(1|band_number), data=subset(ti.f, groups == "Warm Infected"))
glm.tnc <- glm(fever_change~1 +(1|band_number), data=subset(ti.f, groups == "Warm Control"))
glm.stmg <- glm(fever_change~1 +(1|band_number), data=subset(ti.f, groups == "Cold Infected"))
glm.stc <- glm(fever_change~1 +(1|band_number), data=subset(ti.f, groups == "Cold Control"))

summary(glm.all); summary(glm.tnmg); summary(glm.tnc); summary(glm.stmg); summary(glm.stc)

var <- c(0.7357, 0.5979, 0.3482, 1.035, 0.3932) #variance from table above
ci <- c(0.8577, 0.7732, 0.5901, 1.017, 0.6022) #Standard Deviation from table above
g <- c("All Groups", "Warm Infected", "Warm Control", "Cold Infected", "Cold Control") #Groups
temp <- c("all", "Warm", "Warm", "Cold", "Cold")

#new df with variance and error for error bars (min/max)
variability <- data.frame(g,var, ci, temp)
variability$min <- variability$var - variability$ci #new column for lowerbound error
variability$max <- variability$var + variability$ci #new column for upperbound error

g.var <- ggplot(variability %>% filter(temp != "all"), aes(x=g, y=var, shape = g))+
  #geom_col(color="black", size=0.5)+
  geom_point(size=4, alpha = 1)+
  #geom_errorbar(aes(ymin=var, ymax=max), width=0.5)+ #add errorbars representing +/- 1 SD
  labs(x="\nTemperature", y="Variance\n", shape="Temperature", color="Temperature")+
  scale_shape_manual(values = c(0, 1, 2, 3))+
  ylim(c(0,1.5))

g.var
```

```{r Heterogeneity Models}
glm1 <- glm(fever_change ~ 1 + (1|dpi) + (1|band_number), data=ti.f)

ti.f$resid <- resid(glm1)
lm1 <- glm(resid ~ temp*treatment, data=ti.f)
summary(lm1)
plot(allEffects(lm1))
```
Calculate CVs
```{r}
#use fever_score instead of fever_change because it is just a measure of variability
cv.all <- ti.f %>% 
  group_by(groups)%>%
  summarise(bird_cv = sd(fever_score)/mean(fever_score), #this doesn't actually make sense
            bird_sd = sd(fever_score))

#generate error bar values
cv.all$max <- cv.all$bird_cv + cv.all$bird_sd
cv.all$min <- cv.all$bird_cv - cv.all$bird_sd

cv.all
#Graph of CVs
g.cv.all <- ggplot(cv.all, aes(x=groups, y=bird_cv, shape=groups))+
  geom_point(aes(shape=groups), color="black", size=2)+
  scale_shape_manual(values=c(0,1,2,3))+
  #geom_errorbar(aes(ymax=max, ymin=min), color="black", size=0.5, width=0.5)+
  labs(x="Treatment Groups", y="CV", shape="Treatment")+
  scale_fill_manual(values=c("gray85", "white", "gray65", "gray25"))+
  theme_minimal()

g.cv.all

#CV by day
cv.all.day <- ti.f %>%
  group_by(dpi, groups, treatment, temp) %>%
  summarise(
    bird_cv = sd(fever_score) / mean(fever_score),
    bird_sd = sd(fever_score),
    max = bird_cv + bird_sd,
    min = bird_cv - bird_sd
  ) %>%
  ungroup()  # Remove grouping for further operations

cv.allday <- ggplot(cv.all.day, aes(x=dpi, y=bird_cv, shape=groups, color=temp))+
  geom_line(aes(x=dpi, y=bird_cv, linetype = treatment, color=temp))+
  geom_point(size=3)+
  labs(x="Day Post Inoculation", y="CV", linetype= "Treatment Groups", shape="Treatment Groups",
       color = "Temperature")+
  scale_color_manual(values=c("blue", "red"))+
  scale_shape_manual(values=c(0, 15, 1, 16))+
  scale_linetype_manual(values=c("dashed","solid"))+
  ylim(c(0,.1))+
  theme_bw()

cv.allday
```
Histograms
```{r}
treat_names <- c(
  'Cold Infected' = "Infected Cold",
  'Warm Control' = "Control Warm",
  'Warm Infected' = "Infected Warm",
  'Cold Control' = "Control Cold"
)

#Add variable indicating the phago_score mean for each treatment group
f.ti <- ti.f%>%
  group_by(groups)%>%
  mutate(groupmean = mean(fever_change))%>%
  ungroup()

g.ti <- f.ti %>%
  mutate(meanall = mean(fever_change)) %>%
  ungroup()


h.ti <- ti.f %>%
  group_by(groups, dpi) %>%
  mutate(daymean = mean(fever_change))%>%
  ungroup()

#histogram showing variability in fever change across treatment groups
ggplot(f.ti, aes(x=fever_change, fill=groups))+
  geom_histogram(binwidth = 0.5, position="identity", alpha=1, color="black")+
  #geom_density()+
  geom_vline(data = f.ti, aes(xintercept = groupmean, color = "red"), linetype = "dotted",alpha = 1, show.legend=FALSE) + #mean of each group to show differences
  geom_vline(data=g.ti, aes(xintercept = meanall, color = "black"), linetype="dashed", alpha=1, show.legend=FALSE)+ #mean of all groups combined to compare
  scale_fill_manual(values=c( "gray75", "white", "gray35","black"), labels=treat_names)+
  scale_color_manual(values = c("black", "red"), guide = guide_legend(title= NULL))+
  facet_wrap(~groups, nrow=4, labeller = as_labeller(treat_names), scales="fixed")+
  labs(x="Fever Change", y="Count", fill="Treatment")+
  facet_wrap(~groups, nrow=4)
```
Ehh and an animation why not
```{r}
#install.packages("gganimate")
library(gganimate)
#install.packages("gifski")
library(gifski)
#install.packages("magick")
library(magick)

anim_hist<- ggplot(f.ti, aes(x=fever_change, fill=groups))+
  geom_histogram(binwidth = 0.5, position="identity", alpha=1, color="black")+
  geom_vline(data = f.ti, aes(xintercept = groupmean, color = "gray"), linetype = "dashed",alpha = 1, show.legend=FALSE) + #mean of each group to show differences
  geom_vline(data = h.ti, aes(xintercept = daymean, color = "red"), linetype = "dotted",alpha = 1, show.legend=FALSE) + #mean of each group to show differences
  #geom_vline(data=g.ti, aes(xintercept = meanall, color = "black"), linetype="solid", alpha=1, show.legend=FALSE)+ #mean of all groups combined to compare
  scale_fill_manual(values=c( "gray75", "white", "gray35","black"), labels=treat_names)+
  scale_color_manual(values = c("gray", "red", "black"), guide = guide_legend(title= NULL))+
  facet_wrap(~groups, nrow=4, labeller = as_labeller(treat_names), scales="fixed")+
  labs(title = "Fever: DPI {closest_state}", x="Fever Change", y="Count", fill="Treatment")+
  facet_wrap(~groups, nrow=4)+
  transition_states(dpi, transition_length = 2, state_length = 2) +
  exit_fade()+
  theme_bw()

#animate(anim_hist, renderer = gifski_renderer())
```

